name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2
      - name: AddSource
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github
      - name: Pack
        run: dotnet pack --configuration Release
      # Let the workflow fail if the tag version does not match the package version
      - name: Publish
        run: dotnet nuget push bin/Release/BookStoreLib.${{ steps.version.outputs.version-without-v }}.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
